export const dummyRecipes = [
    {
        id: 1,
        description: "Heerlijke surinaamse nasy",
        title: "Surinaamse Nasy",
        prepareTime: 320,
        username: "John Doe",
        difficulty: 3,
        imgUrl: "https://ohmyfoodness.nl/wp-content/uploads/2015/06/surinaamse_nasi_recept-feat-500x500.jpg",
    },
    {
        id: 2,
        description: "Frisse tonijnsalade, alsof het vers uit de zee komt.\"\n",
        title: "Frisse Tonijnsalade",
        prepareTime: 320,
        username: "user000915288",
        difficulty: 1,
        imgUrl: "https://ohmyfoodness.nl/wp-content/uploads/2015/06/surinaamse_nasi_recept-feat-500x500.jpg",
    },
    {
        id: 3,
        description: "Knapperige panini met gesmolten kaas, tonijnsalade, saus en rijk belegd met olijven, pepers en kappertjes.",
        title: "Pittige Panini Tonijn",
        prepareTime: 320,
        username: "user95828639",
        difficulty: 2,
        imgUrl: "https://eetse.nl/media/cache/og_image/uploads/images/zelfgemaakte-lasagne.jpg",
    },
    {
        id: 4,
        description: "Zelfgemaakte Lasagne",
        title: "Lasagne",
        prepareTime: 240,
        username: "user95828639",
        difficulty: 3,
        imgUrl: "https://eetse.nl/media/cache/og_image/uploads/images/zelfgemaakte-lasagne.jpg",
    },
];